//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjWebCsEntityFrameworkAdo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Joueur
    {
        public int RefJoueur { get; set; }
        public string Nom { get; set; }
        public string Poste { get; set; }
        public Nullable<decimal> Salaire { get; set; }
        public Nullable<System.DateTime> Naissance { get; set; }
        public Nullable<int> ReferEquipe { get; set; }
    
        public virtual Equipe Equipe { get; set; }
    }
}
